version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  wordpress:
    container_name: wordpress
    image: wordpress:4.9-php7.2-fpm-alpine
    depends_on:
      - db
    ports:
      - "9000:9000"
    links:
      - db

  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: password

volumes:
  db-data:
