version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./app
    depends_on:
      - db
    volumes:
      - ./app/wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./app/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ../plugins:/var/www/html/wp-content/plugins

  db:
    image: mysql:5
    env_file: .env
    ports:
      - "13306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
